package corbaBanque;


/**
* corbaBanque/IBanqueRemoteOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./corbaBanque/Banque.idl
* lundi 10 novembre 2025 22 h 27 WAT
*/

public interface IBanqueRemoteOperations 
{
  void creerCompte (corbaBanque.Compte cpte);
  void verser (float mt, int code);
  void retirer (float mt, int code);
  corbaBanque.Compte getCompte (int code);
  corbaBanque.Compte[] getComptes ();
  double conversion (float mt);
} // interface IBanqueRemoteOperations
