package corbaBanque;


/**
* corbaBanque/IBanqueRemote.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./corbaBanque/Banque.idl
* lundi 10 novembre 2025 22 h 27 WAT
*/

public interface IBanqueRemote extends IBanqueRemoteOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IBanqueRemote
